"""turns the owner's layered daisu art into the webp parts the dock stacks at runtime.

run from the repo root:  python tools/daisu/export.py

input is Daisu_pngs/ (local only, never committed): twelve 2048x2048 layers that already
share one canvas, so nothing here has to align anything by hand. output is

  public/images/daisu/parts/*.webp   the layers, cropped to the drawing and recoloured
  public/images/daisu/idle.webp      one flat composite for the decorative <img> call sites
  public/images/daisu/bust.webp      her head, for the same
  src/components/daisu/daisuParts.ts the measured geometry, so no percentage is guessed

the art is drawn in black on transparent; the site wants the same lavender the first sketch
used, so every layer is recoloured to INK with its alpha kept. lossless webp is smaller
than quality 85 here because each layer is one flat colour, and it leaves the lines clean.
"""
import io
import json
import os

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "Daisu_pngs")
PARTS = os.path.join(REPO, "public", "images", "daisu", "parts")
ART = os.path.join(REPO, "public", "images", "daisu")
GEOMETRY = os.path.join(REPO, "src", "components", "daisu", "daisuParts.ts")

INK = (232, 229, 246)
# the drawing is this wide in the export; she is never shown above 320 css px, so this is 2x
WIDTH = 760
# the flat composites are decoration at 46 to 290 px
IDLE_WIDTH = 420
BUST_WIDTH = 260

LAYERS = {
    "base": "base/base.png",
    "eyes-default": "olhos/olhos_2_default.png",
    "eyes-smug": "olhos/olhos_1_smug.png",
    "eyes-sharp": "olhos/olhos_3_sharp.png",
    "mouth-closed": "bocas/boca_3_default.png",
    "mouth-open": "bocas/boca_2_open.png",
    "mouth-smug": "bocas/boca_1_open_smug.png",
    "jar-0": "jarro/jarro_0_vazio.png",
    "jar-1": "jarro/jarro_1_um_quarto.png",
    "jar-2": "jarro/jarro_2_2_quartos.png",
    "jar-3": "jarro/jarro_3_3_quartos.png",
    "jar-4": "jarro/jarro_4_full.png",
}

# the bust reaches this far past the rim of the jar, so her collar closes the crop
BUST_BELOW = 40


def load(name):
    return Image.open(os.path.join(SRC, LAYERS[name])).convert("RGBA")


def tint(im):
    a = np.array(im)
    a[:, :, 0], a[:, :, 1], a[:, :, 2] = INK
    return Image.fromarray(a)


def union(boxes):
    return (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))


def write(im, path, width):
    im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path, "WEBP", lossless=True, method=6)
    return os.path.getsize(path)


def main():
    art = {name: load(name) for name in LAYERS}
    box = art["base"].split()[-1].getbbox()
    jar = union([art[f"jar-{i}"].split()[-1].getbbox() for i in range(5)])

    total = 0
    for name, im in art.items():
        total += write(tint(im).crop(box), os.path.join(PARTS, f"{name}.webp"), WIDTH)

    flat = art["base"].copy()
    for part in ("jar-4", "eyes-default", "mouth-closed"):
        flat.alpha_composite(art[part])
    flat = tint(flat)
    total += write(flat.crop(box), os.path.join(ART, "idle.webp"), IDLE_WIDTH)

    # a square portrait: as wide as it is tall, centred on her eyes, cut under the rim of
    # the jar, so her face still reads at the 46px the bubble draws it
    eyes = art["eyes-default"].split()[-1].getbbox()
    middle = (eyes[0] + eyes[2]) // 2
    bottom = jar[1] + BUST_BELOW
    half = (bottom - box[1]) // 2
    total += write(flat.crop((middle - half, box[1], middle + half, bottom)), os.path.join(ART, "bust.webp"), BUST_WIDTH)

    w, h = box[2] - box[0], box[3] - box[1]
    pct = lambda n, of: round(n / of * 10000) / 100
    geometry = {
        "WIDTH": w,
        "HEIGHT": h,
        "JAR": {
            "left": pct(jar[0] - box[0], w),
            "top": pct(jar[1] - box[1], h),
            "width": pct(jar[2] - jar[0], w),
            "height": pct(jar[3] - jar[1], h),
        },
    }
    with io.open(GEOMETRY, "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by tools/daisu/export.py, measured off the art itself; do not edit by hand\n")
        f.write(f"export const ART_WIDTH = {geometry['WIDTH']};\n")
        f.write(f"export const ART_HEIGHT = {geometry['HEIGHT']};\n\n")
        f.write("// the glass she holds, as a share of the drawing: the click target, and what the numbers pop out of\n")
        f.write(f"export const JAR = {json.dumps(geometry['JAR'])};\n")

    print(f"{len(LAYERS)} parts + idle + bust, {total // 1024} KB, drawing {w}x{h}, jar {geometry['JAR']}")


main()
