// generated by tools/daisu/export.py, measured off the art itself; do not edit by hand
export const ART_WIDTH = 1483;
export const ART_HEIGHT = 1796;

// the glass she holds, as a share of the drawing: the click target, and what the numbers pop out of
export const JAR = {"left": 44.98, "top": 52.67, "width": 26.77, "height": 22.94};
